### ISSUE TITLE
 Can you use this to as an embedding model for json?

### ISSUE THREAD

**Issue by reubano** [CTUAvastLab/JsonGrinder.jl#134]
It seems most [embedding-models](https://platform.openai.com/docs/guides/embeddings/embedding-models) are optimized for free text instead of structured data. I've found a suitable [json splitter](https://python.langchain.com/docs/modules/data_connection/document_transformers/recursive_json_splitter/) but have yet to find an embedding model made for json. Can this lib be used to make one?

**Comment by simonmandlik** [comment]
Hi @reubano, thank you for trying out this package.

I would maybe add to @racinmat's reply: We can't provide some pretrained, ready to use embedding models, as is very common in standard NLP nowadays. This is because every JSON dataset might use different schema, and thanks to the way this package works (see the docs), for each dataset we need a different model. This is different to the standard NLP, where regardless of the training dataset, the language is still the same, so the model will work universally.

But as the answer above suggests, it should be straightforward to quickly train your own model.
